function  statsSpiderPlot(statOfSteps,minl,maxl)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here
% d1 = squeeze(sd_m(1,1,:));
% d2 = squeeze(sd_m(2,1,:));
% d3 = squeeze(sd_m(3,1,:));
P = [statOfSteps];

% d1s = squeeze(sdd_std(1,1,:));
% d2s = squeeze(sdd_std(2,1,:));
% d3s = squeeze(sdd_std(3,1,:));


p = [1 2 3 6 7 10 11 14 15 18 4 5 8 9 12 13 16 17 ];
% % minl = min(P(1,p)); maxl = max(P(1,p));
% minl = min(P(:)); maxl = max(P(:));
% axl = [repmat(-max([abs([minl,maxl])]),1,18);
%     repmat(max([abs([minl,maxl])]),1,18)];



% minl = min(abs(P(:))); maxl = max(P(:));
axl = [repmat(minl,1,18);repmat(maxl+10,1,18)];

spider_plot(abs(P(:,p)),...
'AxesLabels', {'S1', 'S2', 'S3', 'S6', 'S7','S10', 'S11', 'S14', 'S15', 'S18','S4', 'S5', 'S8', 'S9', 'S12','S13', 'S16', 'S17'},...
'AxesInterval', 4,...
'AxesPrecision', 0,...
'AxesLimits', axl,...
'AxesLabelsOffset', 0.1,...
'AxesDisplay', 'one',...
'AxesScaling', 'linear',...
'FillOption', {'on'},...
'AxesFont', 'Times New Roman',...
'LabelFont', 'Times New Roman',...
'AxesFontSize', 14,...
'AxesLabelsOffset', 0.15,...
'AxesLabelsEdge', 'none',...
'AxesZoom', 0.7,...
'AxesHorzAlign', 'center',...
'AxesVertAlign', 'middle',...
'LineStyle', {'-.','--','--'},...
'LineWidth', [0.5,0.7,1],...
'LineTransparency', 0.5,...
'Marker', {'o', 'd', 's'},...
'LabelFontSize', 13,...
'FillTransparency', [0.01 0.05 0.075]);

% s.LegendLabels = {'4','5','6'};
% s.LegendHandle.Location = 'northeastoutside';

end