function  statsSpiderPlot_v2(statOfSteps,minl,maxl,stdMaxL,absType)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here
% d1 = squeeze(sd_m(1,1,:));
% d2 = squeeze(sd_m(2,1,:));
% d3 = squeeze(sd_m(3,1,:));
P = [statOfSteps];

% d1s = squeeze(sdd_std(1,1,:));
% d2s = squeeze(sdd_std(2,1,:));
% d3s = squeeze(sdd_std(3,1,:));

legendLines = cell(1,size(P,1));
pltMarkers = cell(1,size(P,1));
rng(0);
lineTypes = ["--",":","-."];
markTypes = ["o","d","s","^","<",">","p","h","v"];
for i = 1:size(P,1)
lr = randi(length(lineTypes),1);
mr = randi(length(markTypes),1);
legendLines{1,i} = char(lineTypes(lr));
pltMarkers{1,i} = char(markTypes(mr));
end

fillTrans = linspace(0.1,0.01,size(P,1));
linWidth =  linspace(0.95,0.5,size(P,1));


p = [1 2 3 6 7 10 11 14 15 18 4 5 8 9 12 13 16 17 ];
% % minl = min(P(1,p)); maxl = max(P(1,p));
% minl = min(P(:)); maxl = max(P(:));
% axl = [repmat(-max([abs([minl,maxl])]),1,18);
%     repmat(max([abs([minl,maxl])]),1,18)];



% minl = min(abs(P(:))); maxl = max(P(:));
if absType
%     axl = [repmat(minl,1,18);repmat(maxl+stdMaxL,1,18)];
     axl = [repmat(minl,1,18);repmat(maxl,1,18)];

spider_plot(abs(P(:,p)),...
'AxesLabels', {'S1', 'S2', 'S3', 'S6', 'S7','S10', 'S11', 'S14', 'S15', 'S18','S4', 'S5', 'S8', 'S9', 'S12','S13', 'S16', 'S17'},...
'AxesInterval', 4,...
'AxesPrecision', 0,...
'AxesLimits', axl,...
'AxesZero', 'on',...
'AxesZeroColor', 'k',...
 'AxesZeroWidth', 1.5,...
'AxesLabelsOffset', 0.1,...
'AxesDisplay', 'one',...
'AxesScaling', 'linear',...
'FillOption', {'on'},...
'AxesFont', 'Times New Roman',...
'LabelFont', 'Times New Roman',...
'AxesFontSize', 14,...
'AxesLabelsOffset', 0.15,...
'AxesLabelsEdge', 'none',...
'AxesZoom', 0.7,...
'AxesHorzAlign', 'center',...
'AxesVertAlign', 'middle',...
'LineStyle', legendLines,...%{'-.','--','--'},...
'LineWidth', linWidth,... %[0.5,0.7,0.5,1]
'LineTransparency', 0.5,...
'Marker', pltMarkers,... %{'o', 'd', 's','>'}
'LabelFontSize', 13,...
'MinorGrid', 'on',...
'FillTransparency', fillTrans); %[0.01 0.05 0.05 0.075]

else

% axl = [repmat(minl-stdMaxL,1,18);repmat(maxl+stdMaxL,1,18)];
axl = [repmat(minl,1,18);repmat(maxl,1,18)];

spider_plot((P(:,p)),...
'AxesLabels', {'S1', 'S2', 'S3', 'S6', 'S7','S10', 'S11', 'S14', 'S15', 'S18','S4', 'S5', 'S8', 'S9', 'S12','S13', 'S16', 'S17'},...
'AxesInterval', 4,...
'AxesPrecision', 0,...
'AxesZero', 'on',...
'AxesZeroColor', 'k',...
 'AxesZeroWidth', 1,...
'AxesLimits', axl,...
'AxesLabelsOffset', 0.1,...
'AxesDisplay', 'one',...
'AxesScaling', 'linear',...
'FillOption', {'on'},...
'AxesFont', 'Times New Roman',...
'LabelFont', 'Times New Roman',...
'AxesFontSize', 14,...
'AxesLabelsOffset', 0.15,...
'AxesLabelsEdge', 'none',...
'AxesZoom', 0.7,...
'AxesHorzAlign', 'center',...
'AxesVertAlign', 'middle',...
'LineStyle', legendLines,...%{'-.','--','--'},...
'LineWidth', linWidth,... %[0.5,0.7,0.5,1]
'LineTransparency', 0.5,...
'Marker', pltMarkers,... %{'o', 'd', 's','>'}
'LabelFontSize', 13,...
'MinorGrid', 'on',...
'FillTransparency', fillTrans); %[0.01 0.05 0.05 0.075]

% s.LegendLabels = {'4','5','6'};
% s.LegendHandle.Location = 'northeastoutside';

end